// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAAmM6qJT7_5lbixJQ-JF0Kb5qNKXEbZs',
    appId: '1:337780233121:web:b0f184a67e09f0dc5d31e0',
    messagingSenderId: '337780233121',
    projectId: 'register2-de1db',
    authDomain: 'register2-de1db.firebaseapp.com',
    storageBucket: 'register2-de1db.appspot.com',
    measurementId: 'G-L5C45DWE21',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiOa6vRrGVlJwHswUumdVayEjpR5zY0hk',
    appId: '1:337780233121:android:becc6ebb958bceb75d31e0',
    messagingSenderId: '337780233121',
    projectId: 'register2-de1db',
    storageBucket: 'register2-de1db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKKeCrXJtCQXaQW3XCWVCCYU8PyG_g_KI',
    appId: '1:337780233121:ios:135624c6fcd06c595d31e0',
    messagingSenderId: '337780233121',
    projectId: 'register2-de1db',
    storageBucket: 'register2-de1db.appspot.com',
    iosClientId: '337780233121-7gl3j1elfdl3ec2r5dkjnsosui6jfdl3.apps.googleusercontent.com',
    iosBundleId: 'com.example.registerCode',
  );
}
